In [ ]:
import numpy as np
import pandas as pd

# **NUMPY**

In [ ]:
#Numpy
array1=np.array([1,2,3,4])
print(array1)

[1 2 3 4]


In [ ]:
array1


array([1, 2, 3, 4])

In [ ]:
array1[2]

3

In [ ]:
array1[0:1]

array([1])

In [ ]:
#checking numpy version
import  numpy as np
arr = np.array([1,3,5,6,8])
print(arr)
print(type(arr))

[1 3 5 6 8]
<class 'numpy.ndarray'>


In [ ]:
#dimension in array
#0-D array
import numpy as np
arr = np.array(29)
print(arr)

29


In [ ]:
#1-D array
import numpy as np
arr = np.array([1,2,4,5,6])
print(arr)

[1 2 4 5 6]


In [ ]:
#2-D array
import numpy as np
arr = np.array([[1,2,3,4],[4,5,7,8]])
print(arr)

[[1 2 3 4]
 [4 5 7 8]]


# **Numpy Ndim()**

In [ ]:
#ndim attribute
import numpy as np
arr1=np.array(43)
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.array([1,2,3,4])
print(arr2.ndim)
print(arr1.ndim)

2
0


In [ ]:
#slicing
import numpy as np
arr=np.array([2,3,4,5,6,78])
print(arr[2:4])

[4 5]


In [ ]:
import numpy as np
import pandas as pd
array1=np.array([1,12,34,56,82])
print(array1)

[ 1 12 34 56 82]


In [ ]:
import numpy as np
array1=np.array([34,56,78,11])
print(array1[1])
print(array1[1:3])

56
[56 78]


In [ ]:
import numpy as np
array2= np.array([[12,23,54,32],[42,45,65,76]])
print(array2)

[[12 23 54 32]
 [42 45 65 76]]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(a.ndim)

2


In [ ]:
import numpy as np
array=np.arange(20)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
import numpy as np
array1=np.arange(20,40)
print(array1)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [ ]:
import numpy as np
array2=np.arange(-20,40,6)
print(array2)

[-20 -14  -8  -2   4  10  16  22  28  34]


In [ ]:
import numpy as np
array3=np.arange(20,40,2)
print(array3)


[20 22 24 26 28 30 32 34 36 38]


# **PANDAS**

In [ ]:
#panads
#Pandas Series
import numpy as np
array1=np.linspace(12,34,16)
print(array1)

In [ ]:
import pandas as pd
demo=[3,6]
demo1=pd.Series(demo)
print(demo1)

0    3
1    6
dtype: int64


In [ ]:
import pandas as pd
demo=[12,15,3]
demo2=pd.Series(demo)
print(demo1)

0    12
1    15
2     3
dtype: int64


In [ ]:
import pandas as pd
demo=[1,2,3,4,5,6,7,8,9,10]
demo3=pd.Series(demo)
print(demo3)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


# **Pandas DataFrame()**

In [ ]:
#Pandas DataFrame
import pandas as pd
dummy={"Name":
       ["Hari","Rahul","Rohit","Ajay","kanika"],
       "Age":[21,23,26,22,34],
       "Branch":['AI','ML','CAD','DS','IOT']}
df=pd.DataFrame(dummy)
print(df)

     Name  Age Branch
0    Hari   21     AI
1   Rahul   23     ML
2   Rohit   26    CAD
3    Ajay   22     DS
4  kanika   34    IOT


In [ ]:
import pandas as pd
deny={"Name":
       ["Atul","Ravi","Sumit","Ayushi","Raj","Palak","Shivani"],
         "Age":[21,23,33,22,45,25,16],
        "Branch":['AI','DS','IT','CSE','IOT','AIML','ML'],
        "Technology":['AWS','Azure','Python','DSA','AIML','UI-path','Google cloud']}
df=pd.DataFrame(deny)
print(df)

      Name  Age Branch    Technology
0     Atul   21     AI           AWS
1     Ravi   23     DS         Azure
2    Sumit   33     IT        Python
3   Ayushi   22    CSE           DSA
4      Raj   45    IOT          AIML
5    Palak   25   AIML       UI-path
6  Shivani   16     ML  Google cloud


In [ ]:
import pandas as pd
data={
    "Calories":[420,380,349,234],
    "Duration":[50,20,30,23]
}
df=pd.DataFrame(data)
print(df)
print(df.loc[2])

   Calories  Duration
0       420        50
1       380        20
2       349        30
3       234        23
Calories    349
Duration     30
Name: 2, dtype: int64


In [ ]:
import pandas as pd
data={
    "Course":["B.tech","BBA","MCA","BA"],
    "Duration":[4,3,2,3]
}
df=pd.DataFrame(data)
print(df)
print(type(df))

   Course  Duration
0  B.tech         4
1     BBA         3
2     MCA         2
3      BA         3
<class 'pandas.core.frame.DataFrame'>


In [ ]:
#Pandas info()
import pandas as pd
data={
    "Employee_Name":["Rohit","Rahul","Ravi","Kanika","Ajay"],
    "Employee_Id":["ARPS","PRMN","ZMPW","PQRS","ABCD"]}
df=pd.DataFrame(data)
demo=df.info()
print(demo)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Employee_Name  5 non-null      object
 1   Employee_Id    5 non-null      object
dtypes: object(2)
memory usage: 208.0+ bytes
None


In [ ]:
#isnull()
import pandas as pd
data={
    "Calories":[420,380,349,234],
    "Duration":[50,20,30,23]
}
df=pd.DataFrame(data)
deny=df.isnull()
print(deny)

   Calories  Duration
0     False     False
1     False     False
2     False     False
3     False     False


In [ ]:
#isnull().sum()
import pandas as pd
data={
    "Employee_Name":["Rohit","Rahul","Ravi","Kanika","Ajay"],
    "Employee_Id":[234,456,768,456,987]}
df=pd.DataFrame(data)
dummy=df.isnull().sum()
print(dummy)

Employee_Name    0
Employee_Id      0
dtype: int64


In [ ]:
# loc & iloc
import pandas as pd
data=[[30,'True'],[20,'False'],[40,'True'],[50,'False']]
label_rows=["Ekta","Aayushi","Samyak","Shreya"]
label_cols=["Akshita","Prakshal"]
df = pd.DataFrame(data, label_rows, label_cols)
print(df.loc["Aayushi","Prakshal"])

False


In [ ]:
import pandas as pd
data={"Name":
    ["Aayushi","Ekta","Samyak","Prakshal","Akshita"],
      "Age":[23,21,19,15,11]}
df=pd.DataFrame(data)
print(df.loc[0:2,"Nme":"Age"])

      Name  Age
0  Aayushi   23
1     Ekta   21
2   Samyak   19


In [ ]:
import pandas as pd
data={"Name":["Aayushi","Ekta","Samyak","Prakshal","Akshita"],
      "Age":[23,21,19,15,11]}
df=pd.DataFrame(data)
print(df.loc[1:4,"Name":"Age"])


       Name  Age
1      Ekta   21
2    Samyak   19
3  Prakshal   15
4   Akshita   11


In [ ]:
# Pandas Drop()
# Remove Defaulter Friends
import pandas as pd
data={"Name":["Rishabh","Pankaj","Ajay","Ishu","Aman","Vasu","Akshat"],
       "Defaulter_friend":["Pankaj","Aman","Rishabh","Diya","Riya","Adrash","Priyanshu"],
       "Best Friend":["Ajay","Ishu","Vasu","Akshat","Shreya","Jyoti","Krishna"]}
df=pd.DataFrame(data)
newdf=df.drop("Defaulter_friend",axis='columns')
print(newdf)


      Name Best Friend
0  Rishabh        Ajay
1   Pankaj        Ishu
2     Ajay        Vasu
3     Ishu      Akshat
4     Aman      Shreya
5     Vasu       Jyoti
6   Akshat     Krishna


In [ ]:
import pandas as pd
deny={"Name":
       ["Atul","Ravi","Sumit","Ayushi","Raj","Palak","Shivani"],
         "Age":[21,23,33,22,45,25,16],
        "Branch":['AI','DS','IT','CSE','IOT','AIML','ML'],
      "Technology":['AWS','Azure','Python','DSA','AIML','UI-path','Google cloud']}
df=pd.DataFrame(deny)
new_df=df.drop("Age",axis=1)
print(new_df)

      Name Branch    Technology
0     Atul     AI           AWS
1     Ravi     DS         Azure
2    Sumit     IT        Python
3   Ayushi    CSE           DSA
4      Raj    IOT          AIML
5    Palak   AIML       UI-path
6  Shivani     ML  Google cloud
